export const splashlogo = require('../assets/splash_logo.png')
export const needLoc = require('../assets/need_loc.png')
export const signUplogin = require('../assets/signup_login.png')
export const confetti = require('../assets/confetti_icon.png')
export const toreceive = require('../assets/to_receive.png')
export const topay = require('../assets/to_pay.png')
export const toship = require('../assets/to_ship.png')
export const editprofile = require('../assets/edit_profile.png')
export const mycards = require('../assets/my_cards.png')
export const myorders = require('../assets/my_orders.png')
export const maskgroup = require('../assets/maskgroup.png')
export const calendar = require('../assets/calendar.png')
export const van = require('../assets/van.png')
export const sara = require('../assets/sara.png')
export const steven = require('../assets/steven.png')
export const henry = require('../assets/henry.png')
export const jane = require('../assets/jane.png')
export const paymentBGC = require('../assets/paymentBGcolor.png')
export const location = require('../assets/location.png')
export const filter = require('../assets/filter_icon.png')
export const search = require('../assets/search.png')
export const resturant = require('../assets/1.png')
export const chop = require('../assets/chop.png')
export const sweet1 = require('../assets/sweet1.png')
export const popupFlag = require('../assets/popup_flag.png')
export const pakFlag = require('../assets/pak_flag.png')



